[owner]
name = "weijia"

[users.weijia]
fullName = "Weijia Wang"
email = "contact@weijia.wang"
gitEmail = "9713184+wegank@users.noreply.github.com"
authorizedKeys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGpByMZOhm7u06dBLvE2OXAe3BBTgS8jrSAm4a7sBWHT",
]
initialPassword = "changeme"

[machines.ctci]
hostName = "ctci"
platform = "loongarch64-linux"
profile = "desktop"
stateVersion = "25.11"

[machines.hyperv]
hostName = "nixos"
platform = "x86_64-linux"
profile = "desktop"
stateVersion = "25.11"

[machines.kimsufi]
hostName = "server"
platform = "x86_64-linux"
profile = "server"
stateVersion = "25.11"

[machines.macbook]
hostName = "MacBook-Air-de-Weijia.local"
platform = "aarch64-darwin"
profile = "desktop"
stateVersion = "25.11"

[machines.parallels]
hostName = "workstation"
platform = "aarch64-linux"
profile = "desktop"
stateVersion = "25.11"

[machines.raspberrypi]
hostName = "raspi"
platform = "aarch64-linux"
profile = "home-server"
stateVersion = "25.11"
