[owner]
name = "weijia"

[users.weijia]
fullName = "Weijia Wang"
email = "contact@weijia.wang"
gitEmail = "9713184+wegank@users.noreply.github.com"
authorizedKeys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGpByMZOhm7u06dBLvE2OXAe3BBTgS8jrSAm4a7sBWHT",
]
initialPassword = "changeme"

[machines.hyperv]
platform = "x86_64-linux"
profile = "desktop"

[machines.kimsufi]
platform = "x86_64-linux"
profile = "server"

[machines.macbook]
platform = "aarch64-darwin"
profile = "desktop"

[machines.parallels]
platform = "aarch64-linux"
profile = "desktop"

[machines.pinephone]
platform = "aarch64-linux"
profile = "mobile"

[machines.raspberrypi]
platform = "aarch64-linux"
profile = "server"
