#!/run/current-system/sw/bin/bash

default=parallels

check_root () {
    if [[ $(id -u) -ne 0 ]]; then
        echo "Please run as root."
        exit 1
    fi
}

format_and_mount () {
    parted -s /dev/sda mklabel gpt
    parted -s /dev/sda mkpart ESP fat32 1MiB 512MiB
    parted -s /dev/sda set 1 esp on
    parted -s /dev/sda mkpart primary ext4 512MiB 100%
    yes | mkfs.fat -F 32 -n boot /dev/sda1
    yes | mkfs.ext4 -L nixos /dev/sda2
    sleep 1
    mount /dev/disk/by-label/nixos /mnt
    mkdir -p /mnt/boot
    mount /dev/disk/by-label/boot /mnt/boot
}

install () {
    nixos-install --no-root-passwd --flake ".#$1"
}

upgrade () {
    nixos-rebuild switch --upgrade --flake ".#$1" --no-write-lock-file
}

if [[ $1 == "upgrade" ]] && [[ $3 == "" ]]; then
    check_root
    upgrade ${2:-$default}
    exit
elif [[ $1 == "install" ]] && [[ $3 == "" ]]; then
    check_root
    format_and_mount
    sleep 1
    install ${2:-$default}
    exit
fi

echo "Unrecognized command."
exit 1
